---
- name: delete credential secrets
  ansible.controller.credential:
    name: Image Builder Secrets
    description: Secrets for Image Builder project
    credential_type: Image Builder Vars
    state: absent
  when:
    - ib_vars is defined
    - ib_vars is changed
    - ib_secrets is defined
    - ib_secrets is success
    - ib_create | d(true) | bool == false

- name: create credential secrets
  ansible.controller.credential:
    name: Image Builder Secrets
    description: Secrets for Image Builder project
    organization: "{{ credential.organization }}"
    credential_type: Image Builder Vars
    inputs: "{{ credential.inputs }}"
    update_secrets: false
    state: present
  register: ib_secrets
  when: ib_create | d(true) | bool == true
