---
- name: create credential types
  ansible.controller.credential_type:
    name: Image Builder Vars
    tower_config_file: "{{ tower_config_file }}"
    description: Variables used in Image Builder project
    inputs: "{{ lookup('file', 'files/input_config.yml') | from_yaml }}"
    injectors: "{{ lookup('file', 'files/injector_config.yml') | from_yaml }}"
    state: present
    kind: cloud
  register: ib_vars
